#! /bin/bash

# ############ Env vars used, set in Travis ############################################################
# AWS_ACCESS_KEY=$AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

# AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
# AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
# CLUSTER_NAME=$CLUSTER_NAME
# SERVICE_BASENAME=$SERVICE_BASENAME
# #   (i.e. my-app; -dev will get appended for the dev environment, making my-app-dev)
# IMAGE_BASENAME=$IMAGE_BASENAME
# #   (i.e. my-app; -dev will get appended for the dev environment, making my-app-dev)

# ## Env vars generated by Travis
# TRAVIS_BRANCH=$TRAVIS_BRANCH
# TRAVIS_COMMIT=$TRAVIS_COMMIT
# ################################################################################################

pushToEcr () {
    eval $(aws ecr get-login --region $AWS_DEFAULT_REGION)
        
    echo "Pushing $2 to $1"
    docker tag $2 $1
    docker push $1
    echo "Pushed $1"

    # for tag in {16.04,latest}; do  
    #   docker tag $IMAGE_NAME ${IMAGE_BASENAME}:${tag}
    #   docker push ${IMAGE_BASENAME}:${tag}
    # done 

}

if [ -z "$TRAVIS_PULL_REQUEST" ] || [ "$TRAVIS_PULL_REQUEST" == "false" ]; then

    ENV_SUFFIX="-demo"
    if [ "$TRAVIS_BRANCH" == "master" ]; then 
      ENV_SUFFIX="-demo"
    elif [ "$TRAVIS_BRANCH" == "staging" ]; then 
      ENV_SUFFIX="-stg"
    elif [ "$TRAVIS_BRANCH" == "production" ]; then 
      ENV_SUFFIX="-prod"
    else 
      return 0;  
    fi

    IMAGE_FULLNAME=$IMAGE_BASENAME$ENV_SUFFIX
    IMAGE_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_BASENAME:$TRAVIS_COMMIT
    SERVICE_FULLNAME=$SERVICE_BASENAME$ENV_SUFFIX

    pushToEcr $IMAGE_URL $IMAGE_FULLNAME
    
    echo "Deploying $TRAVIS_BRANCH on service $SERVICE_FULLNAME"
    deploy-ecs/ecs-deploy.sh -c $CLUSTER_NAME -n $SERVICE_FULLNAME -i $IMAGE_URL -r $AWS_DEFAULT_REGION
fi 
